### ISSUE TITLE
Code review - Matlab syntax highlighting

### ISSUE THREAD

**Issue by Paulie14** [code-critic/cc.net#10]
CC uses some kind of syntax highlight in code reviews, but it is not working properly with Matlab.
One of the main problems is with `A'` symbol, which is used for both for transposition and `'strings'`, but the syntax highlighting understands it always as string.

**Comment by janhybs** [comment]
fixed in 9a990112ffa5af74588f2e73922fdc33f9c8efc5

Example below:
![image](https://user-images.githubusercontent.com/894428/101509219-d4900880-3978-11eb-878f-8fb6a71fad72.png)
