### ISSUE TITLE
Previous comments are hidden on page reload.

### ISSUE THREAD

**Issue by jbrezmorf** [code-critic/cc.net#24]
Reproduce:
1. add a comment to a review
2. go to the main CC page
3. go back to the review -> previous comment is not displayed
4. add a new comment -> both the previous and the new comments are displayed

Possible reason (due to @janhybs):
Comments are loaded only after adding a comment, there is a wrong assumption that no comments are at the initially loaded review.

**Comment by janhybs** [comment]
Comments were loaded, but due to a bug, the first paint received an empty array of comments.
