### ISSUE TITLE
Confusing bahavior of arrows in the comment eddititng box.

### ISSUE THREAD

**Issue by jbrezmorf** [code-critic/cc.net#25]
Arrows switch between submissions, that can be useful, but they should allow moving around the editing box of a comment.

Proposed solution:
change submission switch keys to e.g. Ctrl-PgUp/PgDown there is possibly no conflict.

**Comment by janhybs** [comment]
Set the shortcuts to `Ctrl + PgUp/PgDown`. In some browsers, this shortcut is used for cycling between tabs. So this feature is _practically_ disabled now.
In the future, it would be better to set a proper context where arrow keys are applicable.

**Comment by janhybs** [comment]
Fixed context issue. The final shortcut solution is `ctrl + shift + UP/DOWN` , the other were in conflict with popular browsers
