### ISSUE TITLE
submission of 2 files with the same name

### ISSUE THREAD

**Issue by Paulie14** [code-critic/cc.net#8]
I have no idea how that happened, but student managed to submit 2 files with the same name...weird

![Screenshot from 2020-10-27 09-55-28](https://user-images.githubusercontent.com/5623808/97279036-bfcd3a80-183a-11eb-92e4-30d7a1363e9d.png)

**Comment by janhybs** [comment]
one filename has a space before the `.m`

**Comment by Paulie14** [comment]
My apologies for being blind. Students always surprise with something unexpected..
