### ISSUE TITLE
Improvement - time status of the submission in results table

### ISSUE THREAD

**Issue by Paulie14** [code-critic/cc.net#9]
Since I can now control the opening and closing times of the submission, I would appreciate to see somewhere whether
the student submitted the solution in time or after the "soft deadline".

It could be displayed near the "grading bar" when we open the submission review, so we can decrease the points if the submission is late.

And/or add another column in the 'Grade results', and possibly 'View Results', with values like:
OK x LATE x NONE
OK x LATE(<n days after>) x NONE
IN(time) x AF(ter) x NO(ne)
Green x Orange x Red

We can also think of it as that the points evaluates the program itself and use the submission time status only in the "Grade results" to determine final grades..

A more complicated version would be, if we were able to track also the submission of the fixed version of the program after student receives commented review. Not sure whether it is necessary, it is connected with everyone's grading system.

**Comment by janhybs** [comment]
For now implemented:
![image](https://user-images.githubusercontent.com/894428/101625440-b16a6500-3a1b-11eb-8b0d-2b126eaee7ea.png)
